Vagrant.configure(2) do |config|
 config.vm.box = "centos/7"
#  config.vm.provider :virtualbox do |vb|
#   vb.gui = true
#  end
  config.vm.provision "shell",
       run: "always",
       inline: "yum -y install net-tools"

  config.vm.network "public_network", auto_config: false, bridge: "eth0"
 
  config.vm.provision "shell",
       run: "always",
       inline: "ifconfig eth1 192.168.0.201 netmask 255.255.255.0 up"

  config.vm.provision "shell",
       run: "always",
       inline: "route add default gw 192.168.0.1"
  
  config.vm.hostname = "backuper"

end

